// Code generated by github.com/virzz/structx. DO NOT EDIT.

package ginx

func (s *StoreConfig) WithEnabled(v bool) { s.Enabled = v }
func (s *StoreConfig) WithAddr(v string)  { s.Addr = v }
func (s *StoreConfig) WithPort(v int)     { s.Port = v }
func (s *StoreConfig) WithPass(v string)  { s.Pass = v }
func (s *StoreConfig) WithDB(v int)       { s.DB = v }
